<?php
/**
 * Helpers utility class for plugin-wide common functionality.
 *
 * @package gutenify
 * @subpackage Utilities
 * @since 1.0.0
 */

namespace gutenify;

/**
 * Prevent direct access to the file.
 *
 * Ensures this file is being loaded within the WordPress environment.
 */
defined( 'ABSPATH' ) || exit;

/**
 * Class Helpers
 *
 * Provides commonly used helper functions across the plugin.
 */
class Helpers {

	/**
	 * Returns an array of active block slugs, filtered for customization.
	 *
	 * @return array List of block slugs.
	 */
	public static function active_blocks() {
		$plugin_constants = self::plugin_constants();
		$function_prefix  = $plugin_constants['plugin_main_function_prefix'];

		$blocks = array(
			'templates-browser',
			'advance-slide-item',
			'advance-slider',
			'buttons',
			'button',
			'container',
			'content-toggle-item',
			'faqs',
			'gallery-carousel',
			'grid',
			'grid-item',
			'icon',
			'info-box',
			'map',
			'post-carousel',
			'post-list',
			'section-title',
			'service',
			'slide-item',
			'slider',
			'star-rating',
			'team-member',
			'team',
			'testimonial',
			'testimonials',
			'wc-product-carousel',
			'wc-product-list',
			'notice-bar',
			'countup-v2',
			'icon-v2',
			'countdown-timer',
			'stacking-cards',
			'stacking-card-item',
			'marquee',
			'marquee-item',
			'term-thumbnail',
			'advanced-search',
			'single-product-gallery',
			// 'back-to-top',
			// 'image-marquee',
			// 'image-marquee-item',
			// 'search-toggle',
			// 'search-toggle-container',

			// Optional blocks (can be enabled via filters or config).
			/**
			 * Depricated.
			 */
			'countup',
			// 'link-wrapper',
			// 'masonry',
			// 'custom-list',
			// 'social-share',
			// 'slider-v2',
		);

		// advanced-group is still in development; only enable it when WP_DEBUG is on.
		if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			$blocks[] = 'advanced-group';

			// category-list and filter-sidebar: ported from an unrelated
			// plugin's source ("Firefly Blocks Pro" by ffthemes) that was
			// dropped into src/blocks wholesale — namespace/category/
			// textdomain/asset paths rewritten to this framework's own
			// conventions, PHP registration classes added, and fatal
			// references to a nonexistent Firefly_Blocks_Pro_* class
			// replaced with native WooCommerce/WP calls. Still gated
			// behind WP_DEBUG — keep here until they've had a full
			// editorial/QA pass (copy, icons, WC edge cases) rather than
			// shipping to every site automatically. advanced-search and
			// single-product-gallery share this same porting origin but
			// have moved up into the always-active list above.
			$blocks[] = 'category-list';
			$blocks[] = 'filter-sidebar';
		}

		// These PRO-origin blocks ship in this lite framework but stay
		// gated (PRO active, or the active theme opts in — see
		// Helpers::is_pro_block_active(), checked by each block's own
		// register_block()). Always included here rather than
		// conditionally: active_blocks() runs at plugin-file-load time,
		// before the active theme's own after_setup_theme callback has
		// registered its add_theme_support() calls, so a theme-support
		// check isn't reliable this early. Including them unconditionally
		// only means each block's class file loads (cheap — just defines
		// the class and an `init`-hooked callback); the real gate is
		// checked later, on `init`, once both PRO's activation state and
		// the theme's declared support are reliably known.
		$blocks[] = 'popup';
		$blocks[] = 'hover-card';
		$blocks[] = 'hover-card-normal';
		$blocks[] = 'hover-card-hover';
		$blocks[] = 'wc-product-images-slider';

		return apply_filters( "{$function_prefix}_active_blocks", $blocks );
	}

	/**
	 * Returns plugin constants such as slugs, URLs, versions.
	 *
	 * @return array Associative array of plugin constants.
	 */
	public static function plugin_constants() {
		$defaults = array();

		// Filters allow other components or themes to define these constants.
		$filter_name = 'gutenify_plugin_constants';
		return apply_filters( $filter_name, $defaults );
	}

	/**
	 * Reads the asset file generated by wp-scripts and returns dependencies/version.
	 *
	 * @param string $path Path to the asset file.
	 * @return array Array containing 'dependencies' and 'version'.
	 */
	public static function asset_file_values( $path ) {
		$plugin_constants = self::plugin_constants();
		$version          = $plugin_constants['plugin_main_version'];

		if ( file_exists( $path ) ) {
			return include $path;
		}

		// Fallback if asset file doesn't exist.
		return array(
			'dependencies' => array(),
			'version'      => $version,
		);
	}

	/**
	 * Returns the base URL of the plugin's core directory.
	 *
	 * @return string Trailing-slashed URL.
	 */
	public static function core_base_url() {
		$plugin_constants = self::plugin_constants();
		return trailingslashit( $plugin_constants['core_base_url'] );
	}

	/**
	 * Returns the base filesystem path of the plugin's core directory.
	 *
	 * @return string Trailing-slashed directory path.
	 */
	public static function core_base_dir() {
		$plugin_constants = self::plugin_constants();
		return trailingslashit( $plugin_constants['core_base_dir'] );
	}

	/**
	 * Checks whether the PRO version of the plugin is active.
	 *
	 * @return bool True if PRO version is active.
	 */
	public static function is_pro_active() {
		$constants                   = self::plugin_constants();
		$plugin_main_function_prefix = $constants['plugin_main_function_prefix'];
		return apply_filters( $plugin_main_function_prefix . '_pro_activation_status', false );
	}

	/**
	 * Whether a PRO-origin block hosted in this lite framework should
	 * register: either the PRO plugin is loaded, or the active theme has
	 * opted in via `add_theme_support( '{plugin_main_slug}-pro-blocks' )` —
	 * one flag shared by every block that has made this PRO-to-lite move,
	 * not a per-block flag. Callers must check this on `init` or later
	 * (never from Helpers::active_blocks(), which runs at plugin-file-load
	 * time): by `init`, every active plugin has finished loading (so
	 * `function_exists()` here is reliable regardless of plugin load
	 * order) and the active theme's own `after_setup_theme` callback has
	 * already run (so its `add_theme_support()` call, if any, is visible
	 * to `current_theme_supports()`).
	 *
	 * @return bool
	 */
	public static function is_pro_block_active() {
		$constants                   = self::plugin_constants();
		$plugin_main_function_prefix = $constants['plugin_main_function_prefix'];
		$plugin_main_slug            = $constants['plugin_main_slug'];
		return function_exists( $plugin_main_function_prefix . '_pro' ) || current_theme_supports( $plugin_main_slug . '-pro-blocks' );
	}

	/**
	 * Finds every remote image URL in content matching either rule
	 * `sideload_remote_images()` acts on. Split out so callers that only
	 * need to know "are there any left" (e.g. the background import queue
	 * deciding whether a retry is needed) don't have to duplicate the
	 * pattern logic.
	 *
	 * @param string $content       Raw content (HTML + block comments).
	 * @param string $remote_source See sideload_remote_images().
	 * @return string[] Unique matched URLs, empty array if none.
	 */
	private static function find_remote_image_urls( $content, $remote_source ) {
		$patterns = array(
			// Any host, but a standard uploads/ path (offloaded media / CDN).
			'#https?://[^\s"\'\\\\)]+/wp-content/uploads/[^\s"\'\\\\)]+\.(?:png|jpe?g|gif|webp|svg)#i',
		);

		$remote_host = wp_parse_url( $remote_source, PHP_URL_HOST );
		$remote_host = $remote_host ? $remote_host : $remote_source;

		if ( $remote_host ) {
			$host_parts  = explode( '.', $remote_host );
			$root_domain = implode( '.', array_slice( $host_parts, -2 ) );

			if ( $root_domain ) {
				// Same registrable domain as the source, any path (theme assets, etc).
				$patterns[] = '#https?://[a-z0-9.-]*' . preg_quote( $root_domain, '#' ) . '/[^\s"\'\\\\)]+\.(?:png|jpe?g|gif|webp|svg)#i';
			}
		}

		$urls = array();
		foreach ( $patterns as $pattern ) {
			preg_match_all( $pattern, (string) $content, $matches );
			$urls = array_merge( $urls, $matches[0] );
		}

		return array_unique( $urls );
	}

	/**
	 * Whether content still has at least one image matching
	 * sideload_remote_images()'s rules — i.e. one that either failed to
	 * download on a previous pass, or was never processed at all.
	 *
	 * @param string $content       Raw content (HTML + block comments).
	 * @param string $remote_source See sideload_remote_images().
	 * @return bool
	 */
	public static function has_remote_images( $content, $remote_source = '' ) {
		return ! empty( self::find_remote_image_urls( $content, $remote_source ) );
	}

	/**
	 * Download every image referenced from a remote source (a single
	 * template/kit import, or a full demo-site import) into this site's own
	 * Media Library, and rewrite the content to point at the local copies
	 * instead of the remote site. Covers plain HTML (src="...",
	 * background-image:url(...)) as well as the same URL when it appears
	 * JSON-escaped inside a Gutenberg block comment's attributes (e.g.
	 * wp:gutenify/icon {"url":"https:\/\/...").
	 *
	 * Shared by the single-template importer (Gutenify_Rest::get_template_data())
	 * and the full demo-site importer (Rest_Demo_Importer_V2::create_post()) —
	 * both pull content from the same remote source and need the same fix.
	 *
	 * Two independent match rules cover both ways a demo/template source's
	 * media can be hosted, since either can appear in the same content:
	 *  - Same domain as the source (any path) — a theme's own bundled
	 *    assets, e.g. demo.gutenify.com/<slug>/wp-content/themes/<slug>/
	 *    assets/images/main-banner.jpg, which never lives under uploads/.
	 *  - Any host, but under a standard /wp-content/uploads/ path — covers
	 *    media library uploads offloaded to a different host entirely via
	 *    an offload plugin (e.g. WP Offload Media to S3 —
	 *    demo-gutenify-com.s3.amazonaws.com/wp-content/uploads/...) or a CDN.
	 *
	 * @param string $content        Raw content (HTML + block comments).
	 * @param string $remote_source  A URL or bare domain identifying the
	 *                               remote source; only its registrable
	 *                               domain (last two labels) is used, so
	 *                               any subdomain of it (api., demo., a
	 *                               per-demo subdomain, etc.) is covered.
	 * @return string
	 */
	public static function sideload_remote_images( $content, $remote_source = '' ) {
		$urls = self::find_remote_image_urls( $content, $remote_source );

		if ( empty( $urls ) ) {
			return $content;
		}

		$current_host = wp_parse_url( home_url(), PHP_URL_HOST );

		require_once ABSPATH . 'wp-admin/includes/media.php';
		require_once ABSPATH . 'wp-admin/includes/file.php';
		require_once ABSPATH . 'wp-admin/includes/image.php';

		// Persists for the lifetime of the PHP process, so a single request
		// that processes many posts sharing the same image (a logo/banner
		// reused across pages during a full demo import) downloads it once.
		static $already_sideloaded = array();

		foreach ( $urls as $url ) {
			// Already local (e.g. re-processing already-imported content) — skip.
			if ( $current_host && wp_parse_url( $url, PHP_URL_HOST ) === $current_host ) {
				continue;
			}

			if ( isset( $already_sideloaded[ $url ] ) ) {
				$local_url = $already_sideloaded[ $url ];
			} else {
				$attachment_id = media_sideload_image( html_entity_decode( $url ), 0, null, 'id' );

				if ( is_wp_error( $attachment_id ) ) {
					continue;
				}

				$local_url = wp_get_attachment_url( $attachment_id );

				if ( ! $local_url ) {
					continue;
				}

				$already_sideloaded[ $url ] = $local_url;
			}

			$content = str_replace( $url, $local_url, $content );

			$content = str_replace(
				str_replace( '/', '\/', $url ),
				str_replace( '/', '\/', $local_url ),
				$content
			);
		}

		return $content;
	}
}
