<?php
/**
 * Helpers utility class for plugin-wide common functionality.
 *
 * @package gutenify
 * @subpackage Utilities
 * @since 1.0.0
 */

namespace gutenify;

/**
 * Prevent direct access to the file.
 *
 * Ensures this file is being loaded within the WordPress environment.
 */
defined( 'ABSPATH' ) || exit;

/**
 * Class Helpers
 *
 * Provides commonly used helper functions across the plugin.
 */
class Helpers {

	/**
	 * Returns an array of active block slugs, filtered for customization.
	 *
	 * @return array List of block slugs.
	 */
	public static function active_blocks() {
		$plugin_constants = self::plugin_constants();
		$function_prefix  = $plugin_constants['plugin_main_function_prefix'];

		$blocks = array(
			'templates-browser',
			'advance-slide-item',
			'advance-slider',
			'buttons',
			'button',
			'container',
			'content-toggle-item',
			'faqs',
			'gallery-carousel',
			'grid',
			'grid-item',
			'icon',
			'info-box',
			'map',
			'post-carousel',
			'post-list',
			'section-title',
			'service',
			'slide-item',
			'slider',
			'star-rating',
			'team-member',
			'team',
			'testimonial',
			'testimonials',
			'wc-product-carousel',
			'wc-product-list',
			'notice-bar',
			'countup-v2',
			'icon-v2',
			'countdown-timer',
			'stacking-cards',
			'stacking-card-item',
			'marquee',
			'marquee-item',
			// 'back-to-top',
			// 'image-marquee',
			// 'image-marquee-item',
			// 'search-toggle',
			// 'search-toggle-container',

			// Optional blocks (can be enabled via filters or config).
			/**
			 * Depricated.
			 */
			'countup',
			// 'link-wrapper',
			// 'masonry',
			// 'custom-list',
			// 'social-share',
			// 'slider-v2',
		);

		// advanced-group is still in development; only enable it when WP_DEBUG is on.
		if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			$blocks[] = 'advanced-group';
		}

		// These PRO-origin blocks ship in this lite framework but stay
		// gated (PRO active, or the active theme opts in — see
		// Helpers::is_pro_block_active(), checked by each block's own
		// register_block()). Always included here rather than
		// conditionally: active_blocks() runs at plugin-file-load time,
		// before the active theme's own after_setup_theme callback has
		// registered its add_theme_support() calls, so a theme-support
		// check isn't reliable this early. Including them unconditionally
		// only means each block's class file loads (cheap — just defines
		// the class and an `init`-hooked callback); the real gate is
		// checked later, on `init`, once both PRO's activation state and
		// the theme's declared support are reliably known.
		$blocks[] = 'popup';
		$blocks[] = 'hover-card';
		$blocks[] = 'hover-card-normal';
		$blocks[] = 'hover-card-hover';
		$blocks[] = 'wc-product-images-slider';

		return apply_filters( "{$function_prefix}_active_blocks", $blocks );
	}

	/**
	 * Returns plugin constants such as slugs, URLs, versions.
	 *
	 * @return array Associative array of plugin constants.
	 */
	public static function plugin_constants() {
		$defaults = array();

		// Filters allow other components or themes to define these constants.
		$filter_name = 'gutenify_plugin_constants';
		return apply_filters( $filter_name, $defaults );
	}

	/**
	 * Reads the asset file generated by wp-scripts and returns dependencies/version.
	 *
	 * @param string $path Path to the asset file.
	 * @return array Array containing 'dependencies' and 'version'.
	 */
	public static function asset_file_values( $path ) {
		$plugin_constants = self::plugin_constants();
		$version          = $plugin_constants['plugin_main_version'];

		if ( file_exists( $path ) ) {
			return include $path;
		}

		// Fallback if asset file doesn't exist.
		return array(
			'dependencies' => array(),
			'version'      => $version,
		);
	}

	/**
	 * Returns the base URL of the plugin's core directory.
	 *
	 * @return string Trailing-slashed URL.
	 */
	public static function core_base_url() {
		$plugin_constants = self::plugin_constants();
		return trailingslashit( $plugin_constants['core_base_url'] );
	}

	/**
	 * Returns the base filesystem path of the plugin's core directory.
	 *
	 * @return string Trailing-slashed directory path.
	 */
	public static function core_base_dir() {
		$plugin_constants = self::plugin_constants();
		return trailingslashit( $plugin_constants['core_base_dir'] );
	}

	/**
	 * Checks whether the PRO version of the plugin is active.
	 *
	 * @return bool True if PRO version is active.
	 */
	public static function is_pro_active() {
		$constants                   = self::plugin_constants();
		$plugin_main_function_prefix = $constants['plugin_main_function_prefix'];
		return apply_filters( $plugin_main_function_prefix . '_pro_activation_status', false );
	}

	/**
	 * Whether a PRO-origin block hosted in this lite framework should
	 * register: either the PRO plugin is loaded, or the active theme has
	 * opted in via `add_theme_support( '{plugin_main_slug}-pro-blocks' )` —
	 * one flag shared by every block that has made this PRO-to-lite move,
	 * not a per-block flag. Callers must check this on `init` or later
	 * (never from Helpers::active_blocks(), which runs at plugin-file-load
	 * time): by `init`, every active plugin has finished loading (so
	 * `function_exists()` here is reliable regardless of plugin load
	 * order) and the active theme's own `after_setup_theme` callback has
	 * already run (so its `add_theme_support()` call, if any, is visible
	 * to `current_theme_supports()`).
	 *
	 * @return bool
	 */
	public static function is_pro_block_active() {
		$constants                   = self::plugin_constants();
		$plugin_main_function_prefix = $constants['plugin_main_function_prefix'];
		$plugin_main_slug            = $constants['plugin_main_slug'];
		return function_exists( $plugin_main_function_prefix . '_pro' ) || current_theme_supports( $plugin_main_slug . '-pro-blocks' );
	}
}
